// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace LifeStruct.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserFitness : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserFitness));
        
        string IMigrationMetadata.Id
        {
            get { return "201609140824320_UserFitness"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
