// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace LifeStruct.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TagsName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TagsName));
        
        string IMigrationMetadata.Id
        {
            get { return "201609171248084_Tags-Name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
